import React, { Component } from 'react'
export { listPage } from './ListPage'
export { list } from './List'
export { editForm } from './EditForm'
export { editModal } from './EditModal'
export { detailsPage } from './DetailsPage'
export { details } from './Details'
//export details from './Details'
//export createForm from './CreateForm'
//export deleteForm from './DeleteForm'
